/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *EnterNumCities;
    QLineEdit *CountLabel;
    QPushButton *createPeaks;
    QPushButton *createRibs;
    QPushButton *Answer;
    QLineEdit *p24;
    QLineEdit *p34;
    QLineEdit *p29;
    QLabel *clh2;
    QLineEdit *p69;
    QLabel *clh9;
    QLineEdit *p28;
    QLineEdit *p79;
    QLabel *clv7;
    QLineEdit *p59;
    QLineEdit *p56;
    QLineEdit *p39;
    QLineEdit *p47;
    QLabel *clv8;
    QLabel *clv1;
    QLabel *clv4;
    QLabel *clv6;
    QLineEdit *p68;
    QLabel *d6;
    QLabel *clh6;
    QLineEdit *p45;
    QLineEdit *p26;
    QLabel *clh3;
    QLineEdit *p16;
    QLabel *clv5;
    QLineEdit *p37;
    QLineEdit *p89;
    QLineEdit *p49;
    QLineEdit *p25;
    QLabel *d9;
    QLineEdit *p23;
    QLineEdit *p17;
    QLineEdit *p27;
    QLineEdit *p36;
    QLabel *clh7;
    QLabel *d2;
    QLineEdit *p78;
    QLineEdit *p12;
    QLabel *d4;
    QLineEdit *p14;
    QLabel *d3;
    QLabel *clv3;
    QLabel *clv2;
    QLineEdit *p46;
    QLineEdit *p58;
    QLineEdit *p38;
    QLineEdit *p18;
    QLabel *clh5;
    QLabel *d5;
    QLineEdit *p15;
    QLineEdit *p35;
    QLabel *clh4;
    QLineEdit *p57;
    QLineEdit *p13;
    QLineEdit *p19;
    QLabel *d7;
    QLabel *clv9;
    QLabel *d8;
    QLabel *d1;
    QLabel *clh1;
    QLineEdit *p67;
    QLabel *clh8;
    QLineEdit *p48;
    QLineEdit *p21;
    QLineEdit *p31;
    QLineEdit *p32;
    QLineEdit *p42;
    QLineEdit *p41;
    QLineEdit *p43;
    QLineEdit *p53;
    QLineEdit *p52;
    QLineEdit *p54;
    QLineEdit *p51;
    QLineEdit *p62;
    QLineEdit *p64;
    QLineEdit *p61;
    QLineEdit *p63;
    QLineEdit *p65;
    QLineEdit *p73;
    QLineEdit *p75;
    QLineEdit *p71;
    QLineEdit *p72;
    QLineEdit *p74;
    QLineEdit *p76;
    QLineEdit *p83;
    QLineEdit *p82;
    QLineEdit *p86;
    QLineEdit *p84;
    QLineEdit *p85;
    QLineEdit *p87;
    QLineEdit *p81;
    QLineEdit *p96;
    QLineEdit *p94;
    QLineEdit *p97;
    QLineEdit *p98;
    QLineEdit *p92;
    QLineEdit *p93;
    QLineEdit *p95;
    QLineEdit *p91;
    QLabel *Answer_label;
    QMenuBar *menubar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(720, 796);
        QFont font;
        font.setPointSize(9);
        MainWindow->setFont(font);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        EnterNumCities = new QLabel(centralwidget);
        EnterNumCities->setObjectName(QString::fromUtf8("EnterNumCities"));
        EnterNumCities->setGeometry(QRect(530, 460, 187, 21));
        QFont font1;
        font1.setPointSize(13);
        font1.setBold(false);
        font1.setItalic(true);
        font1.setWeight(50);
        EnterNumCities->setFont(font1);
        EnterNumCities->setStyleSheet(QString::fromUtf8(""));
        CountLabel = new QLineEdit(centralwidget);
        CountLabel->setObjectName(QString::fromUtf8("CountLabel"));
        CountLabel->setGeometry(QRect(520, 500, 191, 25));
        CountLabel->setStyleSheet(QString::fromUtf8(""));
        CountLabel->setAlignment(Qt::AlignCenter);
        createPeaks = new QPushButton(centralwidget);
        createPeaks->setObjectName(QString::fromUtf8("createPeaks"));
        createPeaks->setGeometry(QRect(520, 540, 191, 30));
        QFont font2;
        font2.setPointSize(13);
        font2.setBold(false);
        font2.setWeight(50);
        createPeaks->setFont(font2);
        createPeaks->setCursor(QCursor(Qt::PointingHandCursor));
        createPeaks->setStyleSheet(QString::fromUtf8(""));
        createRibs = new QPushButton(centralwidget);
        createRibs->setObjectName(QString::fromUtf8("createRibs"));
        createRibs->setGeometry(QRect(520, 580, 191, 30));
        QFont font3;
        font3.setPointSize(13);
        createRibs->setFont(font3);
        createRibs->setStyleSheet(QString::fromUtf8(""));
        Answer = new QPushButton(centralwidget);
        Answer->setObjectName(QString::fromUtf8("Answer"));
        Answer->setGeometry(QRect(520, 620, 191, 61));
        Answer->setFont(font3);
        Answer->setStyleSheet(QString::fromUtf8(""));
        p24 = new QLineEdit(centralwidget);
        p24->setObjectName(QString::fromUtf8("p24"));
        p24->setGeometry(QRect(210, 510, 50, 30));
        p24->setMinimumSize(QSize(50, 30));
        p24->setStyleSheet(QString::fromUtf8(""));
        p24->setMaxLength(3);
        p24->setAlignment(Qt::AlignCenter);
        p34 = new QLineEdit(centralwidget);
        p34->setObjectName(QString::fromUtf8("p34"));
        p34->setGeometry(QRect(210, 540, 50, 30));
        p34->setMinimumSize(QSize(50, 30));
        p34->setStyleSheet(QString::fromUtf8(""));
        p34->setMaxLength(3);
        p34->setAlignment(Qt::AlignCenter);
        p29 = new QLineEdit(centralwidget);
        p29->setObjectName(QString::fromUtf8("p29"));
        p29->setGeometry(QRect(460, 510, 50, 30));
        p29->setMinimumSize(QSize(50, 30));
        p29->setStyleSheet(QString::fromUtf8(""));
        p29->setMaxLength(3);
        p29->setAlignment(Qt::AlignCenter);
        clh2 = new QLabel(centralwidget);
        clh2->setObjectName(QString::fromUtf8("clh2"));
        clh2->setGeometry(QRect(110, 450, 50, 30));
        clh2->setMinimumSize(QSize(50, 30));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        clh2->setFont(font4);
        clh2->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh2->setAlignment(Qt::AlignCenter);
        p69 = new QLineEdit(centralwidget);
        p69->setObjectName(QString::fromUtf8("p69"));
        p69->setGeometry(QRect(460, 630, 50, 30));
        p69->setMinimumSize(QSize(50, 30));
        p69->setStyleSheet(QString::fromUtf8(""));
        p69->setMaxLength(3);
        p69->setAlignment(Qt::AlignCenter);
        clh9 = new QLabel(centralwidget);
        clh9->setObjectName(QString::fromUtf8("clh9"));
        clh9->setGeometry(QRect(460, 450, 50, 30));
        clh9->setMinimumSize(QSize(50, 30));
        clh9->setFont(font4);
        clh9->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh9->setAlignment(Qt::AlignCenter);
        p28 = new QLineEdit(centralwidget);
        p28->setObjectName(QString::fromUtf8("p28"));
        p28->setGeometry(QRect(410, 510, 50, 30));
        p28->setMinimumSize(QSize(50, 30));
        p28->setStyleSheet(QString::fromUtf8(""));
        p28->setMaxLength(3);
        p28->setAlignment(Qt::AlignCenter);
        p79 = new QLineEdit(centralwidget);
        p79->setObjectName(QString::fromUtf8("p79"));
        p79->setGeometry(QRect(460, 660, 50, 30));
        p79->setMinimumSize(QSize(50, 30));
        p79->setStyleSheet(QString::fromUtf8(""));
        p79->setMaxLength(3);
        p79->setAlignment(Qt::AlignCenter);
        clv7 = new QLabel(centralwidget);
        clv7->setObjectName(QString::fromUtf8("clv7"));
        clv7->setGeometry(QRect(10, 660, 50, 30));
        clv7->setMinimumSize(QSize(20, 30));
        clv7->setFont(font4);
        clv7->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv7->setAlignment(Qt::AlignCenter);
        p59 = new QLineEdit(centralwidget);
        p59->setObjectName(QString::fromUtf8("p59"));
        p59->setGeometry(QRect(460, 600, 50, 30));
        p59->setMinimumSize(QSize(50, 30));
        p59->setStyleSheet(QString::fromUtf8(""));
        p59->setMaxLength(3);
        p59->setAlignment(Qt::AlignCenter);
        p56 = new QLineEdit(centralwidget);
        p56->setObjectName(QString::fromUtf8("p56"));
        p56->setGeometry(QRect(310, 600, 50, 30));
        p56->setMinimumSize(QSize(50, 30));
        p56->setStyleSheet(QString::fromUtf8(""));
        p56->setMaxLength(3);
        p56->setAlignment(Qt::AlignCenter);
        p39 = new QLineEdit(centralwidget);
        p39->setObjectName(QString::fromUtf8("p39"));
        p39->setGeometry(QRect(460, 540, 50, 30));
        p39->setMinimumSize(QSize(50, 30));
        p39->setStyleSheet(QString::fromUtf8(""));
        p39->setMaxLength(3);
        p39->setAlignment(Qt::AlignCenter);
        p47 = new QLineEdit(centralwidget);
        p47->setObjectName(QString::fromUtf8("p47"));
        p47->setGeometry(QRect(360, 570, 50, 30));
        p47->setMinimumSize(QSize(50, 30));
        p47->setStyleSheet(QString::fromUtf8(""));
        p47->setMaxLength(3);
        p47->setAlignment(Qt::AlignCenter);
        clv8 = new QLabel(centralwidget);
        clv8->setObjectName(QString::fromUtf8("clv8"));
        clv8->setGeometry(QRect(10, 690, 50, 30));
        clv8->setMinimumSize(QSize(20, 30));
        clv8->setFont(font4);
        clv8->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv8->setAlignment(Qt::AlignCenter);
        clv1 = new QLabel(centralwidget);
        clv1->setObjectName(QString::fromUtf8("clv1"));
        clv1->setGeometry(QRect(10, 480, 50, 30));
        clv1->setMinimumSize(QSize(20, 30));
        clv1->setFont(font4);
        clv1->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv1->setAlignment(Qt::AlignCenter);
        clv4 = new QLabel(centralwidget);
        clv4->setObjectName(QString::fromUtf8("clv4"));
        clv4->setGeometry(QRect(10, 570, 50, 30));
        clv4->setMinimumSize(QSize(20, 30));
        clv4->setFont(font4);
        clv4->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv4->setAlignment(Qt::AlignCenter);
        clv6 = new QLabel(centralwidget);
        clv6->setObjectName(QString::fromUtf8("clv6"));
        clv6->setGeometry(QRect(10, 630, 50, 30));
        clv6->setMinimumSize(QSize(20, 30));
        clv6->setFont(font4);
        clv6->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv6->setAlignment(Qt::AlignCenter);
        p68 = new QLineEdit(centralwidget);
        p68->setObjectName(QString::fromUtf8("p68"));
        p68->setGeometry(QRect(410, 630, 50, 30));
        p68->setMinimumSize(QSize(50, 30));
        p68->setStyleSheet(QString::fromUtf8(""));
        p68->setMaxLength(3);
        p68->setAlignment(Qt::AlignCenter);
        d6 = new QLabel(centralwidget);
        d6->setObjectName(QString::fromUtf8("d6"));
        d6->setGeometry(QRect(310, 630, 50, 30));
        d6->setMinimumSize(QSize(50, 30));
        QFont font5;
        font5.setPointSize(15);
        font5.setBold(true);
        font5.setWeight(75);
        d6->setFont(font5);
        d6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d6->setAlignment(Qt::AlignCenter);
        clh6 = new QLabel(centralwidget);
        clh6->setObjectName(QString::fromUtf8("clh6"));
        clh6->setGeometry(QRect(310, 450, 50, 30));
        clh6->setMinimumSize(QSize(50, 30));
        clh6->setFont(font4);
        clh6->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh6->setAlignment(Qt::AlignCenter);
        p45 = new QLineEdit(centralwidget);
        p45->setObjectName(QString::fromUtf8("p45"));
        p45->setGeometry(QRect(260, 570, 50, 30));
        p45->setMinimumSize(QSize(50, 30));
        p45->setStyleSheet(QString::fromUtf8(""));
        p45->setMaxLength(3);
        p45->setAlignment(Qt::AlignCenter);
        p26 = new QLineEdit(centralwidget);
        p26->setObjectName(QString::fromUtf8("p26"));
        p26->setGeometry(QRect(310, 510, 50, 30));
        p26->setMinimumSize(QSize(50, 30));
        p26->setStyleSheet(QString::fromUtf8(""));
        p26->setMaxLength(3);
        p26->setAlignment(Qt::AlignCenter);
        clh3 = new QLabel(centralwidget);
        clh3->setObjectName(QString::fromUtf8("clh3"));
        clh3->setGeometry(QRect(160, 450, 50, 30));
        clh3->setMinimumSize(QSize(50, 30));
        clh3->setFont(font4);
        clh3->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh3->setAlignment(Qt::AlignCenter);
        p16 = new QLineEdit(centralwidget);
        p16->setObjectName(QString::fromUtf8("p16"));
        p16->setGeometry(QRect(310, 480, 50, 30));
        p16->setMinimumSize(QSize(50, 30));
        p16->setStyleSheet(QString::fromUtf8(""));
        p16->setMaxLength(3);
        p16->setAlignment(Qt::AlignCenter);
        clv5 = new QLabel(centralwidget);
        clv5->setObjectName(QString::fromUtf8("clv5"));
        clv5->setGeometry(QRect(10, 600, 50, 30));
        clv5->setMinimumSize(QSize(20, 30));
        clv5->setFont(font4);
        clv5->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv5->setAlignment(Qt::AlignCenter);
        p37 = new QLineEdit(centralwidget);
        p37->setObjectName(QString::fromUtf8("p37"));
        p37->setGeometry(QRect(360, 540, 50, 30));
        p37->setMinimumSize(QSize(50, 30));
        p37->setStyleSheet(QString::fromUtf8(""));
        p37->setMaxLength(3);
        p37->setAlignment(Qt::AlignCenter);
        p89 = new QLineEdit(centralwidget);
        p89->setObjectName(QString::fromUtf8("p89"));
        p89->setGeometry(QRect(460, 690, 50, 30));
        p89->setMinimumSize(QSize(50, 30));
        p89->setStyleSheet(QString::fromUtf8(""));
        p89->setMaxLength(3);
        p89->setAlignment(Qt::AlignCenter);
        p49 = new QLineEdit(centralwidget);
        p49->setObjectName(QString::fromUtf8("p49"));
        p49->setGeometry(QRect(460, 570, 50, 30));
        p49->setMinimumSize(QSize(50, 30));
        p49->setStyleSheet(QString::fromUtf8(""));
        p49->setMaxLength(3);
        p49->setAlignment(Qt::AlignCenter);
        p25 = new QLineEdit(centralwidget);
        p25->setObjectName(QString::fromUtf8("p25"));
        p25->setGeometry(QRect(260, 510, 50, 30));
        p25->setMinimumSize(QSize(50, 30));
        p25->setStyleSheet(QString::fromUtf8(""));
        p25->setMaxLength(3);
        p25->setAlignment(Qt::AlignCenter);
        d9 = new QLabel(centralwidget);
        d9->setObjectName(QString::fromUtf8("d9"));
        d9->setGeometry(QRect(460, 720, 50, 30));
        d9->setMinimumSize(QSize(50, 30));
        d9->setFont(font5);
        d9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d9->setAlignment(Qt::AlignCenter);
        p23 = new QLineEdit(centralwidget);
        p23->setObjectName(QString::fromUtf8("p23"));
        p23->setGeometry(QRect(160, 510, 50, 30));
        p23->setMinimumSize(QSize(50, 30));
        p23->setStyleSheet(QString::fromUtf8(""));
        p23->setMaxLength(3);
        p23->setAlignment(Qt::AlignCenter);
        p17 = new QLineEdit(centralwidget);
        p17->setObjectName(QString::fromUtf8("p17"));
        p17->setGeometry(QRect(360, 480, 50, 30));
        p17->setMinimumSize(QSize(50, 30));
        p17->setStyleSheet(QString::fromUtf8(""));
        p17->setMaxLength(3);
        p17->setAlignment(Qt::AlignCenter);
        p27 = new QLineEdit(centralwidget);
        p27->setObjectName(QString::fromUtf8("p27"));
        p27->setGeometry(QRect(360, 510, 50, 30));
        p27->setMinimumSize(QSize(50, 30));
        p27->setStyleSheet(QString::fromUtf8(""));
        p27->setMaxLength(3);
        p27->setAlignment(Qt::AlignCenter);
        p36 = new QLineEdit(centralwidget);
        p36->setObjectName(QString::fromUtf8("p36"));
        p36->setGeometry(QRect(310, 540, 50, 30));
        p36->setMinimumSize(QSize(50, 30));
        p36->setStyleSheet(QString::fromUtf8(""));
        p36->setMaxLength(3);
        p36->setAlignment(Qt::AlignCenter);
        clh7 = new QLabel(centralwidget);
        clh7->setObjectName(QString::fromUtf8("clh7"));
        clh7->setGeometry(QRect(360, 450, 50, 30));
        clh7->setMinimumSize(QSize(50, 30));
        clh7->setFont(font4);
        clh7->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh7->setAlignment(Qt::AlignCenter);
        d2 = new QLabel(centralwidget);
        d2->setObjectName(QString::fromUtf8("d2"));
        d2->setGeometry(QRect(110, 510, 50, 30));
        d2->setMinimumSize(QSize(50, 30));
        d2->setFont(font5);
        d2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d2->setAlignment(Qt::AlignCenter);
        p78 = new QLineEdit(centralwidget);
        p78->setObjectName(QString::fromUtf8("p78"));
        p78->setGeometry(QRect(410, 660, 50, 30));
        p78->setMinimumSize(QSize(50, 30));
        p78->setStyleSheet(QString::fromUtf8(""));
        p78->setMaxLength(3);
        p78->setAlignment(Qt::AlignCenter);
        p12 = new QLineEdit(centralwidget);
        p12->setObjectName(QString::fromUtf8("p12"));
        p12->setGeometry(QRect(110, 480, 50, 30));
        p12->setMinimumSize(QSize(50, 30));
        p12->setStyleSheet(QString::fromUtf8("border-color: rgb(0, 0, 0);"));
        p12->setMaxLength(3);
        p12->setAlignment(Qt::AlignCenter);
        d4 = new QLabel(centralwidget);
        d4->setObjectName(QString::fromUtf8("d4"));
        d4->setGeometry(QRect(210, 570, 50, 30));
        d4->setMinimumSize(QSize(50, 30));
        d4->setFont(font5);
        d4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d4->setAlignment(Qt::AlignCenter);
        p14 = new QLineEdit(centralwidget);
        p14->setObjectName(QString::fromUtf8("p14"));
        p14->setGeometry(QRect(210, 480, 50, 30));
        p14->setMinimumSize(QSize(50, 30));
        p14->setStyleSheet(QString::fromUtf8(""));
        p14->setMaxLength(3);
        p14->setAlignment(Qt::AlignCenter);
        d3 = new QLabel(centralwidget);
        d3->setObjectName(QString::fromUtf8("d3"));
        d3->setGeometry(QRect(160, 540, 50, 30));
        d3->setMinimumSize(QSize(50, 30));
        d3->setFont(font5);
        d3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d3->setAlignment(Qt::AlignCenter);
        clv3 = new QLabel(centralwidget);
        clv3->setObjectName(QString::fromUtf8("clv3"));
        clv3->setGeometry(QRect(10, 540, 50, 30));
        clv3->setMinimumSize(QSize(20, 30));
        clv3->setFont(font4);
        clv3->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv3->setAlignment(Qt::AlignCenter);
        clv2 = new QLabel(centralwidget);
        clv2->setObjectName(QString::fromUtf8("clv2"));
        clv2->setGeometry(QRect(10, 510, 50, 30));
        clv2->setMinimumSize(QSize(20, 30));
        clv2->setFont(font4);
        clv2->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv2->setAlignment(Qt::AlignCenter);
        p46 = new QLineEdit(centralwidget);
        p46->setObjectName(QString::fromUtf8("p46"));
        p46->setGeometry(QRect(310, 570, 50, 30));
        p46->setMinimumSize(QSize(50, 30));
        p46->setStyleSheet(QString::fromUtf8(""));
        p46->setMaxLength(3);
        p46->setAlignment(Qt::AlignCenter);
        p58 = new QLineEdit(centralwidget);
        p58->setObjectName(QString::fromUtf8("p58"));
        p58->setGeometry(QRect(410, 600, 50, 30));
        p58->setMinimumSize(QSize(50, 30));
        p58->setStyleSheet(QString::fromUtf8(""));
        p58->setMaxLength(3);
        p58->setAlignment(Qt::AlignCenter);
        p38 = new QLineEdit(centralwidget);
        p38->setObjectName(QString::fromUtf8("p38"));
        p38->setGeometry(QRect(410, 540, 50, 30));
        p38->setMinimumSize(QSize(50, 30));
        p38->setStyleSheet(QString::fromUtf8(""));
        p38->setMaxLength(3);
        p38->setAlignment(Qt::AlignCenter);
        p18 = new QLineEdit(centralwidget);
        p18->setObjectName(QString::fromUtf8("p18"));
        p18->setGeometry(QRect(410, 480, 50, 30));
        p18->setMinimumSize(QSize(50, 30));
        p18->setStyleSheet(QString::fromUtf8(""));
        p18->setMaxLength(3);
        p18->setAlignment(Qt::AlignCenter);
        clh5 = new QLabel(centralwidget);
        clh5->setObjectName(QString::fromUtf8("clh5"));
        clh5->setGeometry(QRect(260, 450, 50, 30));
        clh5->setMinimumSize(QSize(50, 30));
        clh5->setFont(font4);
        clh5->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh5->setAlignment(Qt::AlignCenter);
        d5 = new QLabel(centralwidget);
        d5->setObjectName(QString::fromUtf8("d5"));
        d5->setGeometry(QRect(260, 600, 50, 30));
        d5->setMinimumSize(QSize(50, 30));
        d5->setFont(font5);
        d5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d5->setAlignment(Qt::AlignCenter);
        p15 = new QLineEdit(centralwidget);
        p15->setObjectName(QString::fromUtf8("p15"));
        p15->setGeometry(QRect(260, 480, 50, 30));
        p15->setMinimumSize(QSize(50, 30));
        p15->setStyleSheet(QString::fromUtf8(""));
        p15->setMaxLength(3);
        p15->setAlignment(Qt::AlignCenter);
        p35 = new QLineEdit(centralwidget);
        p35->setObjectName(QString::fromUtf8("p35"));
        p35->setGeometry(QRect(260, 540, 50, 30));
        p35->setMinimumSize(QSize(50, 30));
        p35->setStyleSheet(QString::fromUtf8(""));
        p35->setMaxLength(3);
        p35->setAlignment(Qt::AlignCenter);
        clh4 = new QLabel(centralwidget);
        clh4->setObjectName(QString::fromUtf8("clh4"));
        clh4->setGeometry(QRect(210, 450, 50, 30));
        clh4->setMinimumSize(QSize(50, 30));
        clh4->setFont(font4);
        clh4->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh4->setAlignment(Qt::AlignCenter);
        p57 = new QLineEdit(centralwidget);
        p57->setObjectName(QString::fromUtf8("p57"));
        p57->setGeometry(QRect(360, 600, 50, 30));
        p57->setMinimumSize(QSize(50, 30));
        p57->setStyleSheet(QString::fromUtf8(""));
        p57->setMaxLength(3);
        p57->setAlignment(Qt::AlignCenter);
        p13 = new QLineEdit(centralwidget);
        p13->setObjectName(QString::fromUtf8("p13"));
        p13->setGeometry(QRect(160, 480, 50, 30));
        p13->setMinimumSize(QSize(50, 30));
        p13->setStyleSheet(QString::fromUtf8(""));
        p13->setMaxLength(3);
        p13->setAlignment(Qt::AlignCenter);
        p19 = new QLineEdit(centralwidget);
        p19->setObjectName(QString::fromUtf8("p19"));
        p19->setGeometry(QRect(460, 480, 50, 30));
        p19->setMinimumSize(QSize(50, 30));
        p19->setStyleSheet(QString::fromUtf8(""));
        p19->setMaxLength(3);
        p19->setAlignment(Qt::AlignCenter);
        d7 = new QLabel(centralwidget);
        d7->setObjectName(QString::fromUtf8("d7"));
        d7->setGeometry(QRect(360, 660, 50, 30));
        d7->setMinimumSize(QSize(50, 30));
        d7->setFont(font5);
        d7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d7->setAlignment(Qt::AlignCenter);
        clv9 = new QLabel(centralwidget);
        clv9->setObjectName(QString::fromUtf8("clv9"));
        clv9->setGeometry(QRect(10, 720, 50, 30));
        clv9->setMinimumSize(QSize(20, 30));
        clv9->setFont(font4);
        clv9->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clv9->setAlignment(Qt::AlignCenter);
        d8 = new QLabel(centralwidget);
        d8->setObjectName(QString::fromUtf8("d8"));
        d8->setGeometry(QRect(410, 690, 50, 30));
        d8->setMinimumSize(QSize(50, 30));
        d8->setFont(font5);
        d8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d8->setAlignment(Qt::AlignCenter);
        d1 = new QLabel(centralwidget);
        d1->setObjectName(QString::fromUtf8("d1"));
        d1->setGeometry(QRect(60, 480, 50, 30));
        d1->setMinimumSize(QSize(50, 30));
        d1->setFont(font5);
        d1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        d1->setAlignment(Qt::AlignCenter);
        clh1 = new QLabel(centralwidget);
        clh1->setObjectName(QString::fromUtf8("clh1"));
        clh1->setGeometry(QRect(60, 450, 50, 30));
        clh1->setMinimumSize(QSize(50, 30));
        clh1->setFont(font4);
        clh1->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh1->setAlignment(Qt::AlignCenter);
        p67 = new QLineEdit(centralwidget);
        p67->setObjectName(QString::fromUtf8("p67"));
        p67->setGeometry(QRect(360, 630, 50, 30));
        p67->setMinimumSize(QSize(50, 30));
        p67->setStyleSheet(QString::fromUtf8(""));
        p67->setMaxLength(3);
        p67->setAlignment(Qt::AlignCenter);
        clh8 = new QLabel(centralwidget);
        clh8->setObjectName(QString::fromUtf8("clh8"));
        clh8->setGeometry(QRect(410, 450, 50, 30));
        clh8->setMinimumSize(QSize(50, 30));
        clh8->setFont(font4);
        clh8->setStyleSheet(QString::fromUtf8("background-color: rgb(217, 217, 217);"));
        clh8->setAlignment(Qt::AlignCenter);
        p48 = new QLineEdit(centralwidget);
        p48->setObjectName(QString::fromUtf8("p48"));
        p48->setGeometry(QRect(410, 570, 50, 30));
        p48->setMinimumSize(QSize(50, 30));
        p48->setStyleSheet(QString::fromUtf8(""));
        p48->setMaxLength(3);
        p48->setAlignment(Qt::AlignCenter);
        p21 = new QLineEdit(centralwidget);
        p21->setObjectName(QString::fromUtf8("p21"));
        p21->setGeometry(QRect(60, 510, 50, 30));
        p21->setMinimumSize(QSize(50, 30));
        p21->setStyleSheet(QString::fromUtf8(""));
        p21->setMaxLength(3);
        p21->setAlignment(Qt::AlignCenter);
        p31 = new QLineEdit(centralwidget);
        p31->setObjectName(QString::fromUtf8("p31"));
        p31->setGeometry(QRect(60, 540, 50, 30));
        p31->setMinimumSize(QSize(50, 30));
        p31->setStyleSheet(QString::fromUtf8(""));
        p31->setMaxLength(3);
        p31->setAlignment(Qt::AlignCenter);
        p32 = new QLineEdit(centralwidget);
        p32->setObjectName(QString::fromUtf8("p32"));
        p32->setGeometry(QRect(110, 540, 50, 30));
        p32->setMinimumSize(QSize(50, 30));
        p32->setStyleSheet(QString::fromUtf8(""));
        p32->setMaxLength(3);
        p32->setAlignment(Qt::AlignCenter);
        p42 = new QLineEdit(centralwidget);
        p42->setObjectName(QString::fromUtf8("p42"));
        p42->setGeometry(QRect(110, 570, 50, 30));
        p42->setMinimumSize(QSize(50, 30));
        p42->setStyleSheet(QString::fromUtf8(""));
        p42->setMaxLength(3);
        p42->setAlignment(Qt::AlignCenter);
        p41 = new QLineEdit(centralwidget);
        p41->setObjectName(QString::fromUtf8("p41"));
        p41->setGeometry(QRect(60, 570, 50, 30));
        p41->setMinimumSize(QSize(50, 30));
        p41->setStyleSheet(QString::fromUtf8(""));
        p41->setMaxLength(3);
        p41->setAlignment(Qt::AlignCenter);
        p43 = new QLineEdit(centralwidget);
        p43->setObjectName(QString::fromUtf8("p43"));
        p43->setGeometry(QRect(160, 570, 50, 30));
        p43->setMinimumSize(QSize(50, 30));
        p43->setStyleSheet(QString::fromUtf8(""));
        p43->setMaxLength(3);
        p43->setAlignment(Qt::AlignCenter);
        p53 = new QLineEdit(centralwidget);
        p53->setObjectName(QString::fromUtf8("p53"));
        p53->setGeometry(QRect(160, 600, 50, 30));
        p53->setMinimumSize(QSize(50, 30));
        p53->setStyleSheet(QString::fromUtf8(""));
        p53->setMaxLength(3);
        p53->setAlignment(Qt::AlignCenter);
        p52 = new QLineEdit(centralwidget);
        p52->setObjectName(QString::fromUtf8("p52"));
        p52->setGeometry(QRect(110, 600, 50, 30));
        p52->setMinimumSize(QSize(50, 30));
        p52->setStyleSheet(QString::fromUtf8(""));
        p52->setMaxLength(3);
        p52->setAlignment(Qt::AlignCenter);
        p54 = new QLineEdit(centralwidget);
        p54->setObjectName(QString::fromUtf8("p54"));
        p54->setGeometry(QRect(210, 600, 50, 30));
        p54->setMinimumSize(QSize(50, 30));
        p54->setStyleSheet(QString::fromUtf8(""));
        p54->setMaxLength(3);
        p54->setAlignment(Qt::AlignCenter);
        p51 = new QLineEdit(centralwidget);
        p51->setObjectName(QString::fromUtf8("p51"));
        p51->setGeometry(QRect(60, 600, 50, 30));
        p51->setMinimumSize(QSize(50, 30));
        p51->setStyleSheet(QString::fromUtf8(""));
        p51->setMaxLength(3);
        p51->setAlignment(Qt::AlignCenter);
        p62 = new QLineEdit(centralwidget);
        p62->setObjectName(QString::fromUtf8("p62"));
        p62->setGeometry(QRect(110, 630, 50, 30));
        p62->setMinimumSize(QSize(50, 30));
        p62->setStyleSheet(QString::fromUtf8(""));
        p62->setMaxLength(3);
        p62->setAlignment(Qt::AlignCenter);
        p64 = new QLineEdit(centralwidget);
        p64->setObjectName(QString::fromUtf8("p64"));
        p64->setGeometry(QRect(210, 630, 50, 30));
        p64->setMinimumSize(QSize(50, 30));
        p64->setStyleSheet(QString::fromUtf8(""));
        p64->setMaxLength(3);
        p64->setAlignment(Qt::AlignCenter);
        p61 = new QLineEdit(centralwidget);
        p61->setObjectName(QString::fromUtf8("p61"));
        p61->setGeometry(QRect(60, 630, 50, 30));
        p61->setMinimumSize(QSize(50, 30));
        p61->setStyleSheet(QString::fromUtf8(""));
        p61->setMaxLength(3);
        p61->setAlignment(Qt::AlignCenter);
        p63 = new QLineEdit(centralwidget);
        p63->setObjectName(QString::fromUtf8("p63"));
        p63->setGeometry(QRect(160, 630, 50, 30));
        p63->setMinimumSize(QSize(50, 30));
        p63->setStyleSheet(QString::fromUtf8(""));
        p63->setMaxLength(3);
        p63->setAlignment(Qt::AlignCenter);
        p65 = new QLineEdit(centralwidget);
        p65->setObjectName(QString::fromUtf8("p65"));
        p65->setGeometry(QRect(260, 630, 50, 30));
        p65->setMinimumSize(QSize(50, 30));
        p65->setStyleSheet(QString::fromUtf8(""));
        p65->setMaxLength(3);
        p65->setAlignment(Qt::AlignCenter);
        p73 = new QLineEdit(centralwidget);
        p73->setObjectName(QString::fromUtf8("p73"));
        p73->setGeometry(QRect(160, 660, 50, 30));
        p73->setMinimumSize(QSize(50, 30));
        p73->setStyleSheet(QString::fromUtf8(""));
        p73->setMaxLength(3);
        p73->setAlignment(Qt::AlignCenter);
        p75 = new QLineEdit(centralwidget);
        p75->setObjectName(QString::fromUtf8("p75"));
        p75->setGeometry(QRect(260, 660, 50, 30));
        p75->setMinimumSize(QSize(50, 30));
        p75->setStyleSheet(QString::fromUtf8(""));
        p75->setMaxLength(3);
        p75->setAlignment(Qt::AlignCenter);
        p71 = new QLineEdit(centralwidget);
        p71->setObjectName(QString::fromUtf8("p71"));
        p71->setGeometry(QRect(60, 660, 50, 30));
        p71->setMinimumSize(QSize(50, 30));
        p71->setStyleSheet(QString::fromUtf8(""));
        p71->setMaxLength(3);
        p71->setAlignment(Qt::AlignCenter);
        p72 = new QLineEdit(centralwidget);
        p72->setObjectName(QString::fromUtf8("p72"));
        p72->setGeometry(QRect(110, 660, 50, 30));
        p72->setMinimumSize(QSize(50, 30));
        p72->setStyleSheet(QString::fromUtf8(""));
        p72->setMaxLength(3);
        p72->setAlignment(Qt::AlignCenter);
        p74 = new QLineEdit(centralwidget);
        p74->setObjectName(QString::fromUtf8("p74"));
        p74->setGeometry(QRect(210, 660, 50, 30));
        p74->setMinimumSize(QSize(50, 30));
        p74->setStyleSheet(QString::fromUtf8(""));
        p74->setMaxLength(3);
        p74->setAlignment(Qt::AlignCenter);
        p76 = new QLineEdit(centralwidget);
        p76->setObjectName(QString::fromUtf8("p76"));
        p76->setGeometry(QRect(310, 660, 50, 30));
        p76->setMinimumSize(QSize(50, 30));
        p76->setStyleSheet(QString::fromUtf8(""));
        p76->setMaxLength(3);
        p76->setAlignment(Qt::AlignCenter);
        p83 = new QLineEdit(centralwidget);
        p83->setObjectName(QString::fromUtf8("p83"));
        p83->setGeometry(QRect(160, 690, 50, 30));
        p83->setMinimumSize(QSize(50, 30));
        p83->setStyleSheet(QString::fromUtf8(""));
        p83->setMaxLength(3);
        p83->setAlignment(Qt::AlignCenter);
        p82 = new QLineEdit(centralwidget);
        p82->setObjectName(QString::fromUtf8("p82"));
        p82->setGeometry(QRect(110, 690, 50, 30));
        p82->setMinimumSize(QSize(50, 30));
        p82->setStyleSheet(QString::fromUtf8(""));
        p82->setMaxLength(3);
        p82->setAlignment(Qt::AlignCenter);
        p86 = new QLineEdit(centralwidget);
        p86->setObjectName(QString::fromUtf8("p86"));
        p86->setGeometry(QRect(310, 690, 50, 30));
        p86->setMinimumSize(QSize(50, 30));
        p86->setStyleSheet(QString::fromUtf8(""));
        p86->setMaxLength(3);
        p86->setAlignment(Qt::AlignCenter);
        p84 = new QLineEdit(centralwidget);
        p84->setObjectName(QString::fromUtf8("p84"));
        p84->setGeometry(QRect(210, 690, 50, 30));
        p84->setMinimumSize(QSize(50, 30));
        p84->setStyleSheet(QString::fromUtf8(""));
        p84->setMaxLength(3);
        p84->setAlignment(Qt::AlignCenter);
        p85 = new QLineEdit(centralwidget);
        p85->setObjectName(QString::fromUtf8("p85"));
        p85->setGeometry(QRect(260, 690, 50, 30));
        p85->setMinimumSize(QSize(50, 30));
        p85->setStyleSheet(QString::fromUtf8(""));
        p85->setMaxLength(3);
        p85->setAlignment(Qt::AlignCenter);
        p87 = new QLineEdit(centralwidget);
        p87->setObjectName(QString::fromUtf8("p87"));
        p87->setGeometry(QRect(360, 690, 50, 30));
        p87->setMinimumSize(QSize(50, 30));
        p87->setStyleSheet(QString::fromUtf8(""));
        p87->setMaxLength(3);
        p87->setAlignment(Qt::AlignCenter);
        p81 = new QLineEdit(centralwidget);
        p81->setObjectName(QString::fromUtf8("p81"));
        p81->setGeometry(QRect(60, 690, 50, 30));
        p81->setMinimumSize(QSize(50, 30));
        p81->setStyleSheet(QString::fromUtf8(""));
        p81->setMaxLength(3);
        p81->setAlignment(Qt::AlignCenter);
        p96 = new QLineEdit(centralwidget);
        p96->setObjectName(QString::fromUtf8("p96"));
        p96->setGeometry(QRect(310, 720, 50, 30));
        p96->setMinimumSize(QSize(50, 30));
        p96->setStyleSheet(QString::fromUtf8(""));
        p96->setMaxLength(3);
        p96->setAlignment(Qt::AlignCenter);
        p94 = new QLineEdit(centralwidget);
        p94->setObjectName(QString::fromUtf8("p94"));
        p94->setGeometry(QRect(210, 720, 50, 30));
        p94->setMinimumSize(QSize(50, 30));
        p94->setStyleSheet(QString::fromUtf8(""));
        p94->setMaxLength(3);
        p94->setAlignment(Qt::AlignCenter);
        p97 = new QLineEdit(centralwidget);
        p97->setObjectName(QString::fromUtf8("p97"));
        p97->setGeometry(QRect(360, 720, 50, 30));
        p97->setMinimumSize(QSize(50, 30));
        p97->setStyleSheet(QString::fromUtf8(""));
        p97->setMaxLength(3);
        p97->setAlignment(Qt::AlignCenter);
        p98 = new QLineEdit(centralwidget);
        p98->setObjectName(QString::fromUtf8("p98"));
        p98->setGeometry(QRect(410, 720, 50, 30));
        p98->setMinimumSize(QSize(50, 30));
        p98->setStyleSheet(QString::fromUtf8(""));
        p98->setMaxLength(3);
        p98->setAlignment(Qt::AlignCenter);
        p92 = new QLineEdit(centralwidget);
        p92->setObjectName(QString::fromUtf8("p92"));
        p92->setGeometry(QRect(110, 720, 50, 30));
        p92->setMinimumSize(QSize(50, 30));
        p92->setStyleSheet(QString::fromUtf8(""));
        p92->setMaxLength(3);
        p92->setAlignment(Qt::AlignCenter);
        p93 = new QLineEdit(centralwidget);
        p93->setObjectName(QString::fromUtf8("p93"));
        p93->setGeometry(QRect(160, 720, 50, 30));
        p93->setMinimumSize(QSize(50, 30));
        p93->setStyleSheet(QString::fromUtf8(""));
        p93->setMaxLength(3);
        p93->setAlignment(Qt::AlignCenter);
        p95 = new QLineEdit(centralwidget);
        p95->setObjectName(QString::fromUtf8("p95"));
        p95->setGeometry(QRect(260, 720, 50, 30));
        p95->setMinimumSize(QSize(50, 30));
        p95->setStyleSheet(QString::fromUtf8(""));
        p95->setMaxLength(3);
        p95->setAlignment(Qt::AlignCenter);
        p91 = new QLineEdit(centralwidget);
        p91->setObjectName(QString::fromUtf8("p91"));
        p91->setGeometry(QRect(60, 720, 50, 30));
        p91->setMinimumSize(QSize(50, 30));
        p91->setStyleSheet(QString::fromUtf8(""));
        p91->setMaxLength(3);
        p91->setAlignment(Qt::AlignCenter);
        Answer_label = new QLabel(centralwidget);
        Answer_label->setObjectName(QString::fromUtf8("Answer_label"));
        Answer_label->setGeometry(QRect(520, 690, 191, 51));
        Answer_label->setAlignment(Qt::AlignCenter);
        Answer_label->setWordWrap(true);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 720, 21));
        MainWindow->setMenuBar(menubar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "\320\232\320\276\320\274\320\274\320\270\320\262\320\276\321\217\320\266\320\265\321\200", nullptr));
        EnterNumCities->setText(QApplication::translate("MainWindow", "\320\232\320\276\320\273\320\273\320\270\321\207\320\265\321\201\321\202\320\262\320\276 \320\262\320\265\321\200\321\210\320\270\320\275:", nullptr));
        CountLabel->setText(QString());
        createPeaks->setText(QApplication::translate("MainWindow", "\320\222\320\225\320\240\320\250\320\230\320\235\320\253", nullptr));
        createRibs->setText(QApplication::translate("MainWindow", "\320\240\320\225\320\221\320\240\320\220", nullptr));
        Answer->setText(QApplication::translate("MainWindow", "\320\236\320\242\320\222\320\225\320\242", nullptr));
        clh2->setText(QApplication::translate("MainWindow", "2", nullptr));
        clh9->setText(QApplication::translate("MainWindow", "9", nullptr));
        clv7->setText(QApplication::translate("MainWindow", "7", nullptr));
        clv8->setText(QApplication::translate("MainWindow", "8", nullptr));
        clv1->setText(QApplication::translate("MainWindow", "1", nullptr));
        clv4->setText(QApplication::translate("MainWindow", "4", nullptr));
        clv6->setText(QApplication::translate("MainWindow", "6", nullptr));
        d6->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        clh6->setText(QApplication::translate("MainWindow", "6", nullptr));
        clh3->setText(QApplication::translate("MainWindow", "3", nullptr));
        clv5->setText(QApplication::translate("MainWindow", "5", nullptr));
        d9->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        clh7->setText(QApplication::translate("MainWindow", "7", nullptr));
        d2->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        d4->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        d3->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        clv3->setText(QApplication::translate("MainWindow", "3", nullptr));
        clv2->setText(QApplication::translate("MainWindow", "2", nullptr));
        clh5->setText(QApplication::translate("MainWindow", "5", nullptr));
        d5->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        clh4->setText(QApplication::translate("MainWindow", "4", nullptr));
        p13->setText(QString());
        d7->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        clv9->setText(QApplication::translate("MainWindow", "9", nullptr));
        d8->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        d1->setText(QApplication::translate("MainWindow", "\320\235\320\235", nullptr));
        clh1->setText(QApplication::translate("MainWindow", "1", nullptr));
        clh8->setText(QApplication::translate("MainWindow", "8", nullptr));
        p92->setText(QString());
        Answer_label->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
